[project]
name = "liquid-staked-welsh-test"
requirements = []
costs_version = 2

# static analysis
[repl.analysis]
passes = ["check_checker"]

[contracts.liquid-staked-welsh]
path = "contracts/external/liquid-staked-welsh.clar"
depends_on = ["sip010-ft-trait"]

# external
[contracts.welshcorgicoin-token]
path = "contracts/external/welshcorgicoin-token.clar"
depends_on = ["sip010-ft-trait"]


# traits
[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on = []
