[project]
name = "dungeon-master-test"
requirements = []
costs_version = 2

# static analysis
[repl.analysis]
passes = ["check_checker"]

[contracts.dungeon-master]
path = "contracts/dungeon-master.clar"
depends_on = ["proposal-trait", "extension-trait"]

# extentions
[contracts.dme000-governance-token]
path = "contracts/extensions/dme000-governance-token.clar"
depends_on = []

# proposals

[contracts.dmp000-bootstrap]
path = "contracts/proposals/dmp000-bootstrap.clar"
depends_on = [
    "dungeon-master",
    "proposal-trait",
    "extension-trait",
]

# external
[contracts.welshcorgicoin-token]
path = "contracts/external/welshcorgicoin-token.clar"
depends_on = ["sip010-ft-trait", 'dme021-staked-welsh-pool']

# [contracts.leo-token]
# path = "contracts/external/leo-token.clar"
# depends_on = ["sip010-ft-trait"]

# traits
[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
depends_on = []

[contracts.governance-token-trait]
path = "contracts/traits/governance-token-trait.clar"
depends_on = []

[contracts.ownable-trait]
path = "contracts/traits/ownable-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
depends_on = []

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/traits/nft-trait.clar"
depends_on = []

[contracts.ft-trait]
path = "contracts/traits/ft-trait.clar"
depends_on = []
