[project]
name = "dungeon-master-test"
requirements = []
costs_version = 2

# static analysis
[repl.analysis]
passes = ["check_checker"]

[contracts.dungeon-master]
path = "contracts/dungeon-master.clar"
depends_on = []

# extentions
[contracts.early-users-list]
path = "contracts/extensions/early-users-list.clar"
depends_on = []

[contracts.dme000-governance-token]
path = "contracts/extensions/dme000-governance-token.clar"
depends_on = []

# swaps
[contracts.arbitrage-v0]
path = "contracts/swaps/arbitrage-v0.clar"
depends_on = []

# proposals
[contracts.dmp027-airdrop-rewards]
path = "contracts/proposals/dmp027-airdrop-rewards.clar"
depends_on = []

# traits
[contracts.dao-traits-v2]
path = "contracts/traits/dao-traits-v2.clar"
depends_on = []
